// Copyright 2025 John Wang. All rights reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

package pack

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

// ScaffoldConfig configures pack generation.
type ScaffoldConfig struct {
	// SkillsDir is the directory containing skills to pack.
	SkillsDir string

	// PackageName is the Go package name for the generated pack.
	PackageName string

	// PackName is the name of the skill pack.
	PackName string

	// OutputDir is where to write generated files.
	OutputDir string

	// IncludeVersion embeds the git commit hash as version.
	IncludeVersion bool
}

// ScaffoldResult contains the result of pack scaffolding.
type ScaffoldResult struct {
	// OutputPath is the path to the generated pack.go file.
	OutputPath string

	// Skills lists the skills included in the pack.
	Skills []string

	// Version is the embedded version (git commit hash).
	Version string

	// GeneratedAt is when the pack was generated.
	GeneratedAt time.Time
}

// Scaffold generates a Go skill pack from a skills directory.
//
// The generated pack uses go:embed to bundle all SKILL.md files
// and implements the SkillPack interface.
func Scaffold(cfg ScaffoldConfig) (*ScaffoldResult, error) {
	if cfg.SkillsDir == "" {
		cfg.SkillsDir = "skills"
	}
	if cfg.PackageName == "" {
		cfg.PackageName = "skillpack"
	}
	if cfg.PackName == "" {
		cfg.PackName = filepath.Base(cfg.SkillsDir)
	}
	if cfg.OutputDir == "" {
		cfg.OutputDir = "."
	}

	// Discover skills
	skills, err := discoverSkills(cfg.SkillsDir)
	if err != nil {
		return nil, fmt.Errorf("discover skills: %w", err)
	}

	if len(skills) == 0 {
		return nil, fmt.Errorf("no skills found in %s", cfg.SkillsDir)
	}

	// Get version from git if requested
	var version string
	if cfg.IncludeVersion {
		version = getGitCommitHash()
	}

	// Generate pack code
	code, err := generatePackCode(cfg, skills, version)
	if err != nil {
		return nil, fmt.Errorf("generate pack code: %w", err)
	}

	// Format the generated code
	formatted, err := format.Source([]byte(code))
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w", err)
	}

	// Ensure output directory exists
	if err := os.MkdirAll(cfg.OutputDir, 0755); err != nil {
		return nil, fmt.Errorf("create output directory: %w", err)
	}

	// Write the generated file
	outputPath := filepath.Join(cfg.OutputDir, "pack.go")
	//nolint:gosec // G306: Generated code file needs to be readable
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		return nil, fmt.Errorf("write pack.go: %w", err)
	}

	return &ScaffoldResult{
		OutputPath:  outputPath,
		Skills:      skills,
		Version:     version,
		GeneratedAt: time.Now(),
	}, nil
}

// discoverSkills finds all skill directories containing SKILL.md.
func discoverSkills(root string) ([]string, error) {
	var skills []string

	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, err
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		skillPath := filepath.Join(root, entry.Name(), "SKILL.md")
		if _, err := os.Stat(skillPath); err == nil {
			skills = append(skills, entry.Name())
		}
	}

	return skills, nil
}

// getGitCommitHash returns the current git commit hash.
func getGitCommitHash() string {
	cmd := exec.Command("git", "rev-parse", "HEAD")
	output, err := cmd.Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(output))
}

// GetGitCommitHashShort returns the short git commit hash.
func GetGitCommitHashShort() string {
	cmd := exec.Command("git", "rev-parse", "--short", "HEAD")
	output, err := cmd.Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(output))
}

// generatePackCode generates the Go source code for a skill pack.
func generatePackCode(cfg ScaffoldConfig, skills []string, version string) (string, error) {
	tmpl, err := template.New("pack").Parse(packTemplate)
	if err != nil {
		return "", err
	}

	data := struct {
		PackageName string
		PackName    string
		SkillsDir   string
		Skills      []string
		Version     string
		HasVersion  bool
	}{
		PackageName: cfg.PackageName,
		PackName:    cfg.PackName,
		SkillsDir:   cfg.SkillsDir,
		Skills:      skills,
		Version:     version,
		HasVersion:  version != "",
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

const packTemplate = `// Code generated by omniskill pack scaffold; DO NOT EDIT.

package {{.PackageName}}

import (
	"embed"
)

//go:embed {{.SkillsDir}}/*
var skillsFS embed.FS

// Pack implements the SkillPack interface for bundled skills.
type Pack struct{}

// Name returns the pack identifier.
func (Pack) Name() string { return "{{.PackName}}" }

// Version returns the pack version (source commit hash).
func (Pack) Version() string { return "{{.Version}}" }

// FS returns the embedded filesystem containing skills.
func (Pack) FS() embed.FS { return skillsFS }

// Default returns the default Pack instance.
func Default() *Pack { return &Pack{} }

// Skills returns the list of skill names in this pack.
func (Pack) Skills() []string {
	return []string{
		{{- range .Skills}}
		"{{.}}",
		{{- end}}
	}
}
`

// VerifyVersion checks if the pack version matches the source commit.
//
// This is used to ensure derived packs are properly versioned and
// traceable back to their source.
func VerifyVersion(pack SkillPack) error {
	currentCommit := getGitCommitHash()
	packVersion := pack.Version()

	if packVersion == "" {
		return fmt.Errorf("pack has no version")
	}

	if packVersion == "unknown" {
		return fmt.Errorf("pack version is unknown (not in git repo?)")
	}

	if packVersion != currentCommit {
		return fmt.Errorf("pack version %s does not match current commit %s", packVersion, currentCommit)
	}

	return nil
}
